# Generated by Django 5.2.8 on 2026-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors_en',
            field=models.CharField(help_text='Доступные цвета: Черный, Белый, Синий, Красный, Зеленый, Желтый, Серый. Указывайте через запятую, например: "Черный, Белый, Синий"', max_length=200, null=True, verbose_name='Доступные цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors_ru',
            field=models.CharField(help_text='Доступные цвета: Черный, Белый, Синий, Красный, Зеленый, Желтый, Серый. Указывайте через запятую, например: "Черный, Белый, Синий"', max_length=200, null=True, verbose_name='Доступные цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors_uz',
            field=models.CharField(help_text='Доступные цвета: Черный, Белый, Синий, Красный, Зеленый, Желтый, Серый. Указывайте через запятую, например: "Черный, Белый, Синий"', max_length=200, null=True, verbose_name='Доступные цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.CharField(help_text='Доступные цвета: Черный, Белый, Синий, Красный, Зеленый, Желтый, Серый. Указывайте через запятую, например: "Черный, Белый, Синий"', max_length=200, verbose_name='Доступные цвета'),
        ),
    ]
