# Generated by Django 5.2.8 on 2026-01-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(default='We are a modern fashion store offering quality clothing for the whole family. Our mission is to make fashion accessible to everyone.', verbose_name='Описание')),
                ('mission', models.TextField(default='To provide high-quality fashion items at affordable prices', verbose_name='Миссия')),
                ('vision', models.TextField(default='To become the leading fashion retailer in the region', verbose_name='Видение')),
                ('values', models.TextField(default='Quality\nCustomer Service\nInnovation\nSustainability', help_text='Указывайте каждое значение с новой строки', verbose_name='Ценности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (800) 111111111111', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@fashionstore.ru', max_length=254, verbose_name='Email')),
                ('address_city', models.CharField(default='Tashkent', max_length=100, verbose_name='Город')),
                ('address_street', models.CharField(default='Example Street, 1', max_length=200, verbose_name='Улица')),
                ('address_full', models.CharField(default='Tashkent, Example Street, 1', max_length=300, verbose_name='Полный адрес')),
                ('working_hours_weekdays', models.CharField(default='9:00 - 20:00', max_length=50, verbose_name='Рабочие часы (будни)')),
                ('working_hours_weekend', models.CharField(default='10:00 - 18:00', max_length=50, verbose_name='Рабочие часы (выходные)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-star', help_text='Например: fas fa-shipping-fast', max_length=100, verbose_name='Иконка (Font Awesome класс)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Collection', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(default='Discover style and comfort', max_length=200, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(default='View Catalog', max_length=100, verbose_name='Текст кнопки')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Фоновое изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Главный баннер',
                'verbose_name_plural': 'Главный баннер',
            },
        ),
        migrations.CreateModel(
            name='SEOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, verbose_name='Meta заголовок')),
                ('meta_description', models.TextField(default="Buy quality clothing online. Wide selection of men's, women's and children's clothing.", verbose_name='Meta описание')),
                ('meta_keywords', models.CharField(default='clothing, fashion, online store, clothes', max_length=500, verbose_name='Meta ключевые слова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'SEO настройки',
                'verbose_name_plural': 'SEO настройки',
            },
        ),
        migrations.CreateModel(
            name='SocialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, default='#', verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, default='#', verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, default='#', verbose_name='Twitter')),
                ('vk', models.URLField(blank=True, default='#', verbose_name='VK')),
                ('telegram', models.URLField(blank=True, default='#', verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, default='#', verbose_name='WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fashion Store', max_length=200, verbose_name='Название магазина')),
                ('title', models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(default='Your reliable partner in the world of fashion. Quality clothing at affordable prices.', verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Иконка сайта (favicon)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1976d2', help_text='HEX цвет, например: #1976d2', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#ffa726', help_text='HEX цвет, например: #ffa726', max_length=7, verbose_name='Вторичный цвет')),
                ('text_color', models.CharField(default='#333', help_text='HEX цвет, например: #333', max_length=7, verbose_name='Цвет текста')),
                ('background_color', models.CharField(default='#fff', help_text='HEX цвет, например: #fff', max_length=7, verbose_name='Цвет фона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки темы',
                'verbose_name_plural': 'Настройки темы',
            },
        ),
    ]
