# Generated by Django 5.2.8 on 2026-01-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_aboutconfig_contactconfig_feature_heroconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutconfig',
            name='description_en',
            field=models.TextField(default='We are a modern fashion store offering quality clothing for the whole family. Our mission is to make fashion accessible to everyone.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='description_ru',
            field=models.TextField(default='We are a modern fashion store offering quality clothing for the whole family. Our mission is to make fashion accessible to everyone.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='description_uz',
            field=models.TextField(default='We are a modern fashion store offering quality clothing for the whole family. Our mission is to make fashion accessible to everyone.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='mission_en',
            field=models.TextField(default='To provide high-quality fashion items at affordable prices', null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='mission_ru',
            field=models.TextField(default='To provide high-quality fashion items at affordable prices', null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='mission_uz',
            field=models.TextField(default='To provide high-quality fashion items at affordable prices', null=True, verbose_name='Миссия'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='title_en',
            field=models.CharField(default='About Us', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='title_ru',
            field=models.CharField(default='About Us', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='title_uz',
            field=models.CharField(default='About Us', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='values_en',
            field=models.TextField(default='Quality\nCustomer Service\nInnovation\nSustainability', help_text='Указывайте каждое значение с новой строки', null=True, verbose_name='Ценности'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='values_ru',
            field=models.TextField(default='Quality\nCustomer Service\nInnovation\nSustainability', help_text='Указывайте каждое значение с новой строки', null=True, verbose_name='Ценности'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='values_uz',
            field=models.TextField(default='Quality\nCustomer Service\nInnovation\nSustainability', help_text='Указывайте каждое значение с новой строки', null=True, verbose_name='Ценности'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='vision_en',
            field=models.TextField(default='To become the leading fashion retailer in the region', null=True, verbose_name='Видение'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='vision_ru',
            field=models.TextField(default='To become the leading fashion retailer in the region', null=True, verbose_name='Видение'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='vision_uz',
            field=models.TextField(default='To become the leading fashion retailer in the region', null=True, verbose_name='Видение'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_city_en',
            field=models.CharField(default='Tashkent', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_city_ru',
            field=models.CharField(default='Tashkent', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_city_uz',
            field=models.CharField(default='Tashkent', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_full_en',
            field=models.CharField(default='Tashkent, Example Street, 1', max_length=300, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_full_ru',
            field=models.CharField(default='Tashkent, Example Street, 1', max_length=300, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_full_uz',
            field=models.CharField(default='Tashkent, Example Street, 1', max_length=300, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_street_en',
            field=models.CharField(default='Example Street, 1', max_length=200, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_street_ru',
            field=models.CharField(default='Example Street, 1', max_length=200, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='address_street_uz',
            field=models.CharField(default='Example Street, 1', max_length=200, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='working_hours_weekdays_en',
            field=models.CharField(default='9:00 - 20:00', max_length=50, null=True, verbose_name='Рабочие часы (будни)'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='working_hours_weekdays_ru',
            field=models.CharField(default='9:00 - 20:00', max_length=50, null=True, verbose_name='Рабочие часы (будни)'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='working_hours_weekdays_uz',
            field=models.CharField(default='9:00 - 20:00', max_length=50, null=True, verbose_name='Рабочие часы (будни)'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='working_hours_weekend_en',
            field=models.CharField(default='10:00 - 18:00', max_length=50, null=True, verbose_name='Рабочие часы (выходные)'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='working_hours_weekend_ru',
            field=models.CharField(default='10:00 - 18:00', max_length=50, null=True, verbose_name='Рабочие часы (выходные)'),
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='working_hours_weekend_uz',
            field=models.CharField(default='10:00 - 18:00', max_length=50, null=True, verbose_name='Рабочие часы (выходные)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='button_text_en',
            field=models.CharField(default='View Catalog', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='button_text_ru',
            field=models.CharField(default='View Catalog', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='button_text_uz',
            field=models.CharField(default='View Catalog', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='subtitle_en',
            field=models.CharField(default='Discover style and comfort', max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='subtitle_ru',
            field=models.CharField(default='Discover style and comfort', max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='subtitle_uz',
            field=models.CharField(default='Discover style and comfort', max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='title_en',
            field=models.CharField(default='New Collection', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='title_ru',
            field=models.CharField(default='New Collection', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroconfig',
            name='title_uz',
            field=models.CharField(default='New Collection', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_description_en',
            field=models.TextField(default="Buy quality clothing online. Wide selection of men's, women's and children's clothing.", null=True, verbose_name='Meta описание'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_description_ru',
            field=models.TextField(default="Buy quality clothing online. Wide selection of men's, women's and children's clothing.", null=True, verbose_name='Meta описание'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_description_uz',
            field=models.TextField(default="Buy quality clothing online. Wide selection of men's, women's and children's clothing.", null=True, verbose_name='Meta описание'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_keywords_en',
            field=models.CharField(default='clothing, fashion, online store, clothes', max_length=500, null=True, verbose_name='Meta ключевые слова'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_keywords_ru',
            field=models.CharField(default='clothing, fashion, online store, clothes', max_length=500, null=True, verbose_name='Meta ключевые слова'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_keywords_uz',
            field=models.CharField(default='clothing, fashion, online store, clothes', max_length=500, null=True, verbose_name='Meta ключевые слова'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_title_en',
            field=models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, null=True, verbose_name='Meta заголовок'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_title_ru',
            field=models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, null=True, verbose_name='Meta заголовок'),
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='meta_title_uz',
            field=models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, null=True, verbose_name='Meta заголовок'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='description_en',
            field=models.TextField(default='Your reliable partner in the world of fashion. Quality clothing at affordable prices.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='description_ru',
            field=models.TextField(default='Your reliable partner in the world of fashion. Quality clothing at affordable prices.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='description_uz',
            field=models.TextField(default='Your reliable partner in the world of fashion. Quality clothing at affordable prices.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='name_en',
            field=models.CharField(default='Fashion Store', max_length=200, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='name_ru',
            field=models.CharField(default='Fashion Store', max_length=200, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='name_uz',
            field=models.CharField(default='Fashion Store', max_length=200, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='title_en',
            field=models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='title_ru',
            field=models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='title_uz',
            field=models.CharField(default='Fashion Store - Online Clothing Store', max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
