# Generated by Django 6.0.1 on 2026-01-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_aboutconfig_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='M', help_text='Доступные размеры: XS, S, M, L, XL, XXL. Указывайте через запятую, например: "S, M, L, XL"', max_length=200, verbose_name='Доступные размеры'),
        ),
    ]
