# Generated by Django 5.2.8 on 2026-01-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactconfig',
            name='map_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на Яндекс карту, например: https://yandex.uz/maps/-/CLhZvD6F', max_length=500, null=True, verbose_name='URL Яндекс карты'),
        ),
    ]
