# Generated by Django 5.2.8 on 2026-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_contactconfig_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('icon', models.CharField(default='fas fa-star', help_text='Например: fas fa-shipping-fast', max_length=100, verbose_name='Иконка (Font Awesome класс)')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Feature товара',
                'verbose_name_plural': 'Features товаров',
                'ordering': ['order', 'title'],
            },
        ),
    ]
