# Generated by Django 5.2.8 on 2026-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productfeatureconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatureconfig',
            name='text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='productfeatureconfig',
            name='text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='productfeatureconfig',
            name='text_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='productfeatureconfig',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productfeatureconfig',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productfeatureconfig',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
