# Generated by Django 5.2.8 on 2026-01-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productfeatureconfig_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='10+', help_text='Например: 10+, 5000+, 24/7', max_length=50, verbose_name='Значение')),
                ('label', models.CharField(default='Years in the market', max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика "О нас"',
                'verbose_name_plural': 'Статистика "О нас"',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
