# Generated by Django 5.2.8 on 2026-01-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_aboutstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstat',
            name='label_en',
            field=models.CharField(default='Years in the market', max_length=200, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='aboutstat',
            name='label_ru',
            field=models.CharField(default='Years in the market', max_length=200, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='aboutstat',
            name='label_uz',
            field=models.CharField(default='Years in the market', max_length=200, null=True, verbose_name='Подпись'),
        ),
    ]
