# Generated by Django 5.2.8 on 2026-01-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_aboutstat_label_en_aboutstat_label_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroconfig',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='Укажите URL изображения, если не загружаете файл', null=True, verbose_name='URL фонового изображения'),
        ),
        migrations.AlterField(
            model_name='heroconfig',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение или укажите URL ниже', null=True, upload_to='config/', verbose_name='Фоновое изображение'),
        ),
    ]
