# Generated by Django 5.2.8 on 2026-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_heroconfig_background_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutconfig',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение или укажите URL ниже', null=True, upload_to='config/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='aboutconfig',
            name='image_url',
            field=models.URLField(blank=True, help_text='Укажите URL изображения, если не загружаете файл', null=True, verbose_name='URL изображения'),
        ),
    ]
