# Generated by Django 5.2.8 on 2026-01-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_aboutconfig_image_aboutconfig_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='Токен бота от @BotFather', max_length=200, verbose_name='Токен бота')),
                ('group_chat_id', models.CharField(blank=True, help_text='ID группы или чата для отправки уведомлений (например: -1001234567890)', max_length=100, verbose_name='ID группы/чата')),
                ('is_active', models.BooleanField(default=False, help_text='Включить отправку уведомлений в Telegram', verbose_name='Активен')),
                ('notify_new_orders', models.BooleanField(default=True, verbose_name='Уведомлять о новых заказах')),
                ('notify_status_changes', models.BooleanField(default=True, verbose_name='Уведомлять об изменении статуса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Telegram',
                'verbose_name_plural': 'Настройки Telegram',
            },
        ),
    ]
