# Generated by Django 5.2.8 on 2026-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_telegramconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('order', 'Вопрос по заказу'), ('product', 'Вопрос по товару'), ('delivery', 'Доставка'), ('return', 'Возврат'), ('other', 'Другое')], max_length=50, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сообщение из контактов',
                'verbose_name_plural': 'Сообщения из контактов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='notify_contact_messages',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о сообщениях из контактов'),
        ),
    ]
