# Generated by Django 5.2.8 on 2026-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
    ]
