# Generated by Django 5.2.8 on 2026-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_faq_answer_en_faq_answer_ru_faq_answer_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, default='', help_text='Доступные размеры: XS, S, M, L, XL, XXL. Указывайте через запятую, например: "S, M, L, XL"', max_length=200, verbose_name='Доступные размеры'),
        ),
    ]
