# Generated by Django 5.2.8 on 2026-05-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_available_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroconfig',
            options={'verbose_name': 'Главная страница — баннер', 'verbose_name_plural': 'Главная страница — баннер'},
        ),
    ]
