# Generated by Django 6.0.7 on 2026-07-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_available_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='От @BotFather. Если пусто — используется TELEGRAM_BOT_TOKEN из окружения.', max_length=200, verbose_name='Токен бота')),
                ('is_active', models.BooleanField(default=False, verbose_name='Включить уведомления в Telegram')),
                ('notify_new_orders', models.BooleanField(default=True, verbose_name='Сообщать о новых заказах')),
                ('notify_status_changes', models.BooleanField(default=True, verbose_name='Сообщать о смене статуса заказа')),
                ('notify_contact_messages', models.BooleanField(default=True, verbose_name='Сообщать о сообщениях с формы «Контакты»')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Telegram — настройки',
                'verbose_name_plural': 'Telegram — настройки',
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(db_index=True, help_text='Число из @userinfobot или после привязки бота.', verbose_name='ID чата в Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Ник в Telegram')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Как подписать в списке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Telegram — получатель',
                'verbose_name_plural': 'Telegram — кому слать',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_placed', 'Новый заказ'), ('order_status_changed', 'Смена статуса'), ('contact_message', 'Контакты')], max_length=64, verbose_name='Событие')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=32, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Очередь Telegram',
                'verbose_name_plural': 'Очередь Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='store_notif_status_f32bce_idx')],
            },
        ),
    ]
