# Generated by Django 6.0.1 on 2026-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_heroconfig_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Условные единицы: на витрине цена в сумах = это значение × SPA_PRICE_UZS_MULTIPLIER (по умолчанию 10 000).', max_digits=10, verbose_name='Цена'),
        ),
    ]
