# Generated by Django 5.2.8 on 2026-05-29 20:26

from django.db import migrations, models


def migrate_legacy_telegram_config(apps, schema_editor):
    TelegramConfig = apps.get_model('store', 'TelegramConfig')
    TelegramNotificationSettings = apps.get_model('store', 'TelegramNotificationSettings')
    TelegramSubscriber = apps.get_model('store', 'TelegramSubscriber')

    legacy = TelegramConfig.objects.filter(is_active=True).first()
    if not legacy:
        return

    if TelegramNotificationSettings.objects.exists():
        return

    TelegramNotificationSettings.objects.create(
        is_active=legacy.is_active,
        notify_new_orders=legacy.notify_new_orders,
        notify_status_changes=legacy.notify_status_changes,
        notify_contact_messages=legacy.notify_contact_messages,
    )
    gid = (legacy.group_chat_id or '').strip()
    if gid:
        try:
            chat_id = int(gid)
        except ValueError:
            return
        TelegramSubscriber.objects.create(
            telegram_chat_id=chat_id,
            display_name='Migrated from TelegramConfig',
            is_active=True,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_price_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBindIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Nonce')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Telegram: привязка (intent)',
                'verbose_name_plural': 'Telegram: привязки (intent)',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Включить постановку уведомлений в очередь (отправка воркером Celery).', verbose_name='Канал Telegram активен')),
                ('notify_new_orders', models.BooleanField(default=True, verbose_name='Новые заказы')),
                ('notify_status_changes', models.BooleanField(default=True, verbose_name='Смена статуса заказа')),
                ('notify_contact_messages', models.BooleanField(default=True, verbose_name='Сообщения из контактов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Telegram: настройки канала',
                'verbose_name_plural': 'Telegram: настройки канала',
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(db_index=True, verbose_name='Telegram chat_id')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Telegram: подписчик',
                'verbose_name_plural': 'Telegram: подписчики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_placed', 'Новый заказ'), ('order_status_changed', 'Смена статуса'), ('contact_message', 'Контакты')], max_length=64, verbose_name='Событие')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=32, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Telegram: outbox',
                'verbose_name_plural': 'Telegram: outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='store_notif_status_f32bce_idx')],
            },
        ),
        migrations.RunPython(migrate_legacy_telegram_config, noop_reverse),
    ]
