# Generated by Django 5.2.8 on 2026-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_telegram_notification_pipeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationoutbox',
            options={'ordering': ['-created_at'], 'verbose_name': 'Очередь Telegram (отладка)', 'verbose_name_plural': 'Очередь Telegram (отладка)'},
        ),
        migrations.AlterModelOptions(
            name='telegrambindintent',
            options={'verbose_name': 'Сессия привязки по ссылке', 'verbose_name_plural': 'Сессии привязки (служебное)'},
        ),
        migrations.AlterModelOptions(
            name='telegramnotificationsettings',
            options={'verbose_name': 'Telegram — настройки', 'verbose_name_plural': 'Telegram — настройки'},
        ),
        migrations.AlterModelOptions(
            name='telegramsubscriber',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram — получатель', 'verbose_name_plural': 'Telegram — кому слать'},
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Пока выключено — заказы и контакты не ставятся в очередь на отправку.', verbose_name='Включить уведомления в Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='notify_contact_messages',
            field=models.BooleanField(default=True, verbose_name='Сообщать о новых сообщениях с формы «Контакты»'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='notify_new_orders',
            field=models.BooleanField(default=True, verbose_name='Сообщать о новых заказах'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='notify_status_changes',
            field=models.BooleanField(default=True, verbose_name='Сообщать о смене статуса заказа'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Как подписать в списке'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='telegram_chat_id',
            field=models.BigIntegerField(db_index=True, help_text='Число: напишите боту @userinfobot в Telegram — он ответит вашим Id. Или привязка по кнопке ниже в «Настройках».', verbose_name='ID чата в Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ник в Telegram'),
        ),
    ]
