# Generated by Django 5.2.8 on 2026-05-29 20:55

from django.db import migrations, models


def copy_bot_token_from_legacy(apps, schema_editor):
    TelegramConfig = apps.get_model('store', 'TelegramConfig')
    TelegramNotificationSettings = apps.get_model('store', 'TelegramNotificationSettings')
    legacy = TelegramConfig.objects.filter(is_active=True).first()
    if not legacy:
        legacy = TelegramConfig.objects.exclude(bot_token='').first()
    if not legacy:
        return
    token = (legacy.bot_token or '').strip()
    if not token:
        return
    row = TelegramNotificationSettings.objects.filter(is_active=True).first()
    if not row:
        row = TelegramNotificationSettings.objects.order_by('pk').first()
    if not row:
        return
    if (getattr(row, 'bot_token', '') or '').strip():
        return
    row.bot_token = token[:200]
    row.save(update_fields=['bot_token'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_telegram_admin_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationsettings',
            name='bot_token',
            field=models.CharField(blank=True, help_text='От @BotFather. Можно указать здесь — владельцу не нужен доступ к .env на сервере. Если пусто, используется переменная окружения TELEGRAM_BOT_TOKEN (если задана).', max_length=200, verbose_name='Токен бота'),
        ),
        migrations.RunPython(copy_bot_token_from_legacy, noop_reverse),
    ]
